GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "3787428"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "dheeraj"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"dheeraj",
    "number":"243343"
}

###
GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/id_to_replace